name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - run: mv .env.example .env
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn check-format
      - run: yarn check-types
